
// ── Dados fictícios (50 notícias, ordenadas por data mais recente primeiro) ──
const allNews = [
{ cat: "Home Appliances", title: "For Appliance Buyers, the Journey Breaks Down When the Repair Process Begins", summary: "LG’s weakest post-purchase moment is not product setup or delivery, but the point when owners need technical help and discover how hard service is to secure.", author: "Davi Zimbardi", date: "May 19, 2026", img: "./articles/lgrepair_article/lgrepair.png", link: "./articles/lgrepair_article/lgrepair_article.html" },
{ cat: "Automotives", title: "BYD’s biggest breakdown comes after the sale, when routine service turns into a dead end", summary: "The historic agreement includes tax incentives and the creation of a national charging network with over 5,000 points across the country.", author: "Ana Beatriz Costa", date: "May 18, 2026", img: "./articles/byd_postsales_article/bydsales.png", link: "./articles/byd_postsales_article/byd_postsales_article.html" },
{ cat: "Automotives", title: "BYD Reviews Receive Strong Consumer Approval and Highlight Efficiency in After-Sales Service", summary: "Customers praise the Chinese automaker’s service, transparency, and agility during maintenance appointments", author: "Vitor Perrone", date: "May 19, 2026", img: "./articles/byd_article/Notícia BYD_html_ad38ae59d59396a8.png", link: "./articles/byd_article/byd_article.html" },
{ cat: "Technology", title: "LG Faces Recurring Criticism Over Delivery Delays and Communication Failures With Customers", summary: "Consumers report missed deadlines, lack of order updates, and difficulty obtaining clear answers from support", author: "Vitor Perrone", date: "May 19, 2026", img: "./articles/lg_article/entrega_atraso.png", link: "./articles/lg_article/lg_article.html" },
{ cat: "Science", title: "Brazilian Space Agency confirms launch of environmental monitoring satellite for September", summary: "The SGDC-2 satellite will be capable of monitoring deforestation in real time and assisting in the fight against wildfires in the Amazon.", author: "Pedro Alves", date: "May 17, 2026", img: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=400&q=70" },
{ cat: "Culture", title: "São Paulo film festival sets attendance record with 280,000 visitors in seven days", summary: "This year's edition paid tribute to Latin American cinema and screened over 400 films from 60 countries across 45 venues.", author: "Camila Rocha", date: "May 16, 2026", img: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=400&q=70" },
{ cat: "Sports", title: "Brazil secures Women's World Cup semifinal spot with epic comeback against Germany", summary: "With two second-half goals, the Brazilian squad overcame the European favorites and advanced to the decisive stage of the tournament.", author: "João Paulo Lima", date: "May 16, 2026", img: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=400&q=70" },
{ cat: "Environment", title: "Amazon deforestation drops 42% in the first quarter of 2026, INPE report shows", summary: "Data reveals a historic decline compared to the same period last year, driven by increased enforcement in priority areas.", author: "Fernanda Gomes", date: "May 15, 2026", img: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=400&q=70" },
{ cat: "Technology", title: "Google launches quantum computing platform accessible to Brazilian researchers and startups", summary: "The initiative provides 100 qubits of cloud processing power free of charge for academic and technology innovation projects.", author: "Lucas Ferreira", date: "May 15, 2026", img: "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=400&q=70" },
{ cat: "Health", title: "Pioneering study maps the gut microbiome of Brazilians and reveals significant regional differences", summary: "The research involved 12,000 participants from across the country and may help develop personalized treatments for chronic diseases.", author: "Dra. Letícia Souza", date: "May 14, 2026", img: "https://images.unsplash.com/photo-1576086213369-97a306d36557?w=400&q=70" },
{ cat: "Economy", title: "Brazilian soybean exports hit all-time record in the first four months of 2026", summary: "Strong demand from China drives a surge in overseas sales, with 18% growth compared to the same period in 2025.", author: "Ricardo Torres", date: "May 14, 2026", img: "https://images.unsplash.com/photo-1560493676-04071c5f467b?w=400&q=70" },
{ cat: "Automotives", title: "First flying car certified by ANAC completes inaugural flight over São Paulo", summary: "The aeromobile vehicle developed by Rio-based startup AeroBR covered 22 km in 8 minutes, marking a historic milestone in urban mobility.", author: "Thiago Nunes", date: "May 13, 2026", img: "https://images.unsplash.com/photo-1569629743817-70d8db6c323b?w=400&q=70" },
{ cat: "Science", title: "Scientists discover new bioluminescent amphibian species in the Brazilian Pantanal", summary: "The discovery, published in Nature, expands knowledge of Brazilian biodiversity and raises questions about the evolution of bioluminescence.", author: "Dra. Ana Flor", date: "May 13, 2026", img: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=400&q=70" },
{ cat: "Technology", title: "São Paulo startup creates intelligent recycling system that sorts waste with 99.7% accuracy", summary: "Using computer vision and robotic arms, the technology promises to transform the solid waste management sector in Brazil.", author: "Beatriz Santos", date: "May 12, 2026", img: "https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?w=400&q=70" },
{ cat: "Culture", title: "Generative art exhibition brings together AI-created and human works at MASP in unprecedented collaboration", summary: "The show questions the limits of creativity and authorship in the digital age, curated by artist Hélio Oiticica Jr.", author: "Camila Rocha", date: "May 12, 2026", img: "https://images.unsplash.com/photo-1561214115-f2f134cc4912?w=400&q=70" },
{ cat: "Health", title: "Ministry of Health launches national campaign against childhood obesity with ambitious targets for 2030", summary: "The program includes school meal reform, mandatory physical activity and nutrition education in all public schools across the country.", author: "Dr. Rafael Mendes", date: "May 11, 2026", img: "https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=400&q=70" },
{ cat: "Environment", title: "Doce River shows signs of environmental recovery eleven years after the Mariana disaster", summary: "Technical reports indicate the gradual return of fish and riparian vegetation along stretches of the river, though researchers warn full recovery will take decades.", author: "Fernanda Gomes", date: "May 11, 2026", img: "https://images.unsplash.com/photo-1470770841072-f978cf4d019e?w=400&q=70" },
{ cat: "Sports", title: "Brazilian judoka wins world championship three times in a row, becoming the greatest athlete in the sport's history", summary: "At just 23, Rafaela Guimarães defeated Japan's Abe in the Paris final and entered the record books of Olympic sport.", author: "João Paulo Lima", date: "May 10, 2026", img: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400&q=70" },
{ cat: "Economy", title: "Brazilian fintechs raise R$ 4.2 billion in international investment round in the first half of the year", summary: "Brazil cements its position as Latin America's largest fintech ecosystem, attracting capital from American, European and Asian funds.", author: "Mariana Oliveira", date: "May 10, 2026", img: "https://images.unsplash.com/photo-1563986768494-4dee2763ff3f?w=400&q=70" },
{ cat: "Technology", title: "Meta launches augmented reality glasses with 3D holograms that eliminate the need for physical screens", summary: "The device, announced at the Connect event, promises to replace smartphones and monitors within five years, according to CEO Mark Zuckerberg.", author: "Lucas Ferreira", date: "May 9, 2026", img: "https://images.unsplash.com/photo-1622979135225-d2ba269cf1ac?w=400&q=70" },
{ cat: "Science", title: "UNICAMP researchers develop graphene battery that recharges in under two minutes", summary: "The innovation could revolutionize electric vehicles and mobile devices, storing twice the energy of conventional lithium batteries.", author: "Pedro Alves", date: "May 9, 2026", img: "https://images.unsplash.com/photo-1605020420620-20c943cc4669?w=400&q=70" },
{ cat: "Automotives", title: "Tesla opens factory in Bahia and promises 8,000 direct jobs by end of 2027", summary: "Gigafactory Salvador will be the company's second largest electric vehicle plant in the southern hemisphere, producing 200,000 cars per year.", author: "Ana Beatriz Costa", date: "May 8, 2026", img: "https://images.unsplash.com/photo-1561361058-c24e01238a46?w=400&q=70" },
{ cat: "Culture", title: "João Gilberto receives posthumous tribute at Latin Grammy with unreleased album restored by AI", summary: "Recordings found in the family's archives were processed and completed by an AI model trained on the work of the Bahian singer.", author: "Camila Rocha", date: "May 8, 2026", img: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&q=70" },
{ cat: "Environment", title: "COP32 held in Belém approves billion-dollar fund for tropical forest preservation", summary: "The historic agreement commits developed nations to contribute US$ 200 billion annually until 2035 for the protection of the world's tropical forests.", author: "Fernanda Gomes", date: "May 7, 2026", img: "https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?w=400&q=70" },
{ cat: "Health", title: "SUS incorporates new Alzheimer's drug capable of slowing disease progression by 35%", summary: "Approved by ANVISA, the medication will be made available free of charge at health clinics and represents a major advance for 1.7 million Brazilians living with the disease.", author: "Dra. Letícia Souza", date: "May 7, 2026", img: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&q=70" },
{ cat: "Sports", title: "Palmeiras defeats Flamengo in historic final to win the Copa Libertadores for the fifth time", summary: "In a packed Maracanã, Palmeiras won on penalties after a 2–2 draw at the end of regular time and extra time.", author: "João Paulo Lima", date: "May 6, 2026", img: "https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=400&q=70" },
{ cat: "Technology", title: "Apple announces iPhone 18 with 4th-generation neural chip and battery lasting three days of heavy use", summary: "The new models also feature a 200MP camera with 20x optical zoom and health capabilities that measure blood glucose without a finger prick.", author: "Beatriz Santos", date: "May 6, 2026", img: "https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?w=400&q=70" },
{ cat: "Economy", title: "Unemployment in Brazil falls to 6.1%, the lowest rate in 22 years, according to IBGE", summary: "Job creation in industry and agribusiness drives the historic decline, though economists warn that informality remains high.", author: "Ricardo Torres", date: "May 5, 2026", img: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=400&q=70" },
{ cat: "Science", title: "Brazilian mission to the South Atlantic collects unprecedented data on ocean currents and climate change", summary: "A 90-day expedition aboard the research vessel Vital Brazil reveals concerning changes in thermohaline circulation patterns.", author: "Dr. Marcos Viana", date: "May 5, 2026", img: "https://images.unsplash.com/photo-1505118380757-91f5f5632de0?w=400&q=70" },
{ cat: "Automotives", title: "New Fiat Strada Hybrid leads sales for the fourth consecutive month, consolidating compact segment dominance", summary: "The hybrid model reaches a 28% market share in the compact pickup segment, surpassing even the automaker's most optimistic projections.", author: "Thiago Nunes", date: "May 4, 2026", img: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=400&q=70" },
{ cat: "Culture", title: "Northeastern author wins International Booker Prize with novel about drought and the resilience of the people of Ceará", summary: "Wendell Fiuza becomes the first Brazilian writer to win the prestigious British prize, with the book set to be translated into 40 languages.", author: "Camila Rocha", date: "May 4, 2026", img: "https://images.unsplash.com/photo-1524578271613-d550eacf6090?w=400&q=70" },
{ cat: "Environment", title: "Bill on zero emissions for heavy industries advances in the Federal Senate", summary: "The proposal sets progressive CO₂ reduction targets through 2040 and establishes heavy fines for companies that fail to meet the established limits.", author: "Fernanda Gomes", date: "May 3, 2026", img: "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=400&q=70" },
{ cat: "Health", title: "Study finds that 30 minutes of daily walking reduces cardiovascular disease risk by 40%", summary: "A 15-year longitudinal study following 50,000 Brazilians confirms that moderate physical activity is more effective than many preventive medications.", author: "Dr. Rafael Mendes", date: "May 3, 2026", img: "https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?w=400&q=70" },
{ cat: "Technology", title: "Deeptech startup creates material that captures CO₂ from the air and converts it into clean synthetic fuel", summary: "The technology, developed in partnership with FAPESP, can be deployed anywhere and costs 70% less than conventional methods.", author: "Lucas Ferreira", date: "May 2, 2026", img: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=400&q=70" },
{ cat: "Sports", title: "Volleyball legend Giba inducted into the FIVB Hall of Fame alongside other greats of the sport", summary: "A ceremony in Rome honors the contribution of the athlete from Curitiba to the global development of men's volleyball over two decades.", author: "João Paulo Lima", date: "May 2, 2026", img: "https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?w=400&q=70" },
{ cat: "Economy", title: "Brazil's GDP grows 3.8% in the first quarter of 2026, driven by agribusiness and digital services", summary: "The result surpasses economists' estimates and puts the country on track for its best performance in a decade, according to IBGE.", author: "Mariana Oliveira", date: "May 1, 2026", img: "https://images.unsplash.com/photo-1589758438368-0ad531db3366?w=400&q=70" },
{ cat: "Science", title: "Brazilian physicists confirm the existence of a new subatomic particle predicted by the Standard Model", summary: "An experiment at the CERN particle accelerator detects the B2 scalar boson, closing one of the last open chapters in high-energy physics.", author: "Pedro Alves", date: "May 1, 2026", img: "https://images.unsplash.com/photo-1507413245164-6160d8298b31?w=400&q=70" },
{ cat: "Automotives", title: "BYD launches electric truck line for the Brazilian market with a range of 600 km per charge", summary: "The vehicles were specially adapted for Brazilian road conditions and arrive at prices competitive with diesel models.", author: "Thiago Nunes", date: "Apr 30, 2026", img: "https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=400&q=70" },
{ cat: "Culture", title: "Brazilian Cinematheque digitizes 15,000 rare films and makes the collection available online for free", summary: "The historical preservation project, funded by the Ministry of Culture, gives anyone with internet access the chance to explore Brazil's audiovisual heritage.", author: "Camila Rocha", date: "Apr 30, 2026", img: "https://images.unsplash.com/photo-1485846234645-a62644f84728?w=400&q=70" },
{ cat: "Environment", title: "Solar energy surpasses natural gas to become Brazil's second largest source of electricity", summary: "The historic milestone arrives five years ahead of schedule, cementing Brazil as a renewable energy powerhouse with 28% of its energy matrix from solar photovoltaics.", author: "Fernanda Gomes", date: "Apr 29, 2026", img: "https://images.unsplash.com/photo-1509391366360-2e959784a276?w=400&q=70" },
{ cat: "Health", title: "ANVISA approves first biopharmaceutical fully developed and produced in Brazil for rheumatoid arthritis treatment", summary: "The drug, the result of 15 years of research at FIOCRUZ, will cost 80% less than imported alternatives and will benefit 1.2 million patients in the public health system.", author: "Dra. Letícia Souza", date: "Apr 29, 2026", img: "https://images.unsplash.com/photo-1585435557343-3b092031a831?w=400&q=70" },
{ cat: "Technology", title: "Microsoft launches AI integrated into Windows 12 that learns user habits and anticipates their needs", summary: "The Copilot Adaptive system learns from user behavior to streamline workflows, reduce distractions and suggest relevant actions.", author: "Beatriz Santos", date: "Apr 28, 2026", img: "https://images.unsplash.com/photo-1633419461186-7d40a38105ec?w=400&q=70" },
{ cat: "Sports", title: "Brazilian athletics breaks five South American records at the Rio de Janeiro Grand Prix in a historic night", summary: "With a packed stadium, the new generation of Brazilian track and field athletes signals the country is ready to compete for medals at the 2028 Brisbane Olympics.", author: "João Paulo Lima", date: "Apr 28, 2026", img: "https://images.unsplash.com/photo-1552674605-db6ffd4facb5?w=400&q=70" },
{ cat: "Economy", title: "Petrobras announces discovery of new pre-salt oil field with estimated reserves of 3 billion barrels", summary: "The find, in the Santos Basin, is expected to raise national output by 400,000 barrels per day once it comes online, projected for 2030.", author: "Ricardo Torres", date: "Apr 27, 2026", img: "https://images.unsplash.com/photo-1518459031867-a89b944bffe4?w=400&q=70" },
{ cat: "Science", title: "Lab in Ceará synthesizes plant-based protein with the taste and texture of beef", summary: "The breakthrough could transform the food industry and dramatically reduce the environmental impact of animal protein production in Brazil.", author: "Dr. Marcos Viana", date: "Apr 27, 2026", img: "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=400&q=70" },
{ cat: "Automotives", title: "Volkswagen revives the Beetle as a compact, affordable electric car for the Brazilian market", summary: "The new Brazilian Beetle will offer a 350 km range, 25-minute charging and a starting price of R$ 89,000, taking on popular segment rivals.", author: "Ana Beatriz Costa", date: "Apr 26, 2026", img: "https://images.unsplash.com/photo-1502877338535-766e1452684a?w=400&q=70" },
{ cat: "Culture", title: "Museum of Tomorrow in Rio opens permanent wing dedicated to artificial intelligence and the future of humanity", summary: "The 2,000 m² interactive space presents the perspectives of experts, artists and philosophers on the challenges and opportunities of the age of intelligent machines.", author: "Camila Rocha", date: "Apr 26, 2026", img: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=70" },
{ cat: "Health", title: "Brazilian mental health app surpasses 10 million users and expands to 12 countries across Latin America", summary: "The Mente Clara platform offers AI-powered therapy, guided meditation and access to psychologists, and has been cited by the WHO as a model to be replicated.", author: "Dr. Rafael Mendes", date: "Apr 25, 2026", img: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=400&q=70" },
{ cat: "Environment", title: "Coral Vivo program records 18% recovery of coral reefs along the Bahia coastline in just two years", summary: "A pioneering coral transplant and cultivation initiative in marine nurseries is restoring life to the largest coral reef system in the South Atlantic.", author: "Fernanda Gomes", date: "Apr 25, 2026", img: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=400&q=70" },
];

const PER_PAGE = 10;
let currentPage = 1;
const totalPages = Math.ceil(allNews.length / PER_PAGE);

function renderPage(page) {
currentPage = page;
const start = (page - 1) * PER_PAGE;
const items = allNews.slice(start, start + PER_PAGE);

document.getElementById('page-count').textContent = `Page ${page} of ${totalPages}`;

const container = document.getElementById('listing-container');
container.innerHTML = items.map(n => `
    <a class="listing-item" href="${n.link? n.link : "#"}">
    <img class="listing-item-img" src="${n.img}" alt="${n.cat}" loading="lazy" />
    <div class="listing-item-body">
        <p class="listing-item-cat">${n.cat}</p>
        <p class="listing-item-title">${n.title}</p>
        <p class="listing-item-summary">${n.summary}</p>
        <p class="listing-item-meta">${n.date} · ${n.author}</p>
    </div>
    </a>
`).join('');

renderPagination();
window.scrollTo({ top: 0, behavior: 'smooth' });
}

function renderPagination() {
const nav = document.getElementById('pagination');
let html = '';

// Prev
html += `<button class="nav-btn" ${currentPage === 1 ? 'disabled' : ''} onclick="renderPage(${currentPage - 1})">← Previous</button>`;

// Pages
for (let i = 1; i <= totalPages; i++) {
    if (i === 1 || i === totalPages || Math.abs(i - currentPage) <= 1) {
    html += `<button class="${i === currentPage ? 'active' : ''}" onclick="renderPage(${i})">${i}</button>`;
    } else if (Math.abs(i - currentPage) === 2) {
    html += `<span class="dots">…</span>`;
    }
}

// Next
html += `<button class="nav-btn" ${currentPage === totalPages ? 'disabled' : ''} onclick="renderPage(${currentPage + 1})">Next →</button>`;

nav.innerHTML = html;
}

// Init
renderPage(1);
